[project]
name = "convertflow-app"
version = "1.0.0"
description = "ConvertFlow cross-platform Python app"
requires-python = ">=3.13,<3.14"
dependencies = [
  "flet>=0.86.5,<0.87.0",
]

[tool.flet]
product = "ConvertFlow"
project = "ConvertFlow"
artifact = "ConvertFlow"
org = "com.convertflow"
bundle_id = "com.convertflow.app"
company = "ConvertFlow"
description = "Convert files online with ConvertFlow."
copyright = "Copyright 2026 ConvertFlow"
python_version = "3.13"
splash_color = "#111827"

[tool.flet.app]
path = "src"
module = "main.py"

[tool.flet.windows]
artifact = "ConvertFlow"

[tool.flet.macos]
artifact = "ConvertFlow"
target_arch = ["arm64", "x86_64"]
dependencies = ["flet-webview>=0.1.0,<1.0.0"]

[tool.flet.android]
target_arch = ["arm64-v8a", "armeabi-v7a", "x86_64"]
dependencies = ["flet-webview>=0.1.0,<1.0.0"]

[tool.flet.ios]
dependencies = ["flet-webview>=0.1.0,<1.0.0"]

[tool.flet.android.manifest_application]
usesCleartextTraffic = "false"
